spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:competence
    username: root
    password: rootroot
    driver-class-name: org.h2.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
